sudo: required

services:
  - docker

before_install:
  - docker-compose -f dev.yml up -d --build andino
  - docker exec andino bash /etc/ckan_init.d/make_test_conf.sh

script:
  - docker exec andino bash -c "source /usr/lib/ckan/default/bin/activate && /etc/ckan_init.d/run_tests.sh"
