version: '2'
services:
    nginx:
      image: datosgobar/portal-base-nginx:latest
      ports:
        - 80:80
      depends_on:
        - andino
      environment:
        - CKAN_HOST=andino
    andino:
        build: .
        container_name: andino
        ports:
          - 8800:8800
        depends_on:
           - db
           - solr
           - redis
           - postfix
        volumes:
          - $PWD:/dev-app
          - production_ini:/etc/ckan/default/
    db:
      image: postgres:9.5
      environment:
        - POSTGRES_USER=ckan
        - POSTGRES_PASSWORD=ckan
        - POSTGRES_DB=ckan
    redis:
      image: redis:3.2.7-alpine
    solr:
      image: datosgobar/portal-base-solr:latest
    postfix:
      image: catatnight/postfix
      ports:
        - "25:25"
        - "587:587"

volumes:
  production_ini: {}
