version: '2'
services:
    andino:
        build: ./ckan-img
        container_name: andino
        ports:
          - 80:80
          - 8800:8800
        depends_on:
           - db
           - solr
        networks:
          - andino-network
        volumes:
          - $PWD:/dev-app
    db:
        build: ./postgresql-img
        container_name: db
        networks:
          - andino-network
    solr:
        build: ./solr-img
        container_name: solr
        networks:
          - andino-network
networks:
  andino-network:
