version: '2'
services:
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
          - 80:80
        depends_on:
          - andino
        networks:
          - andino-network
    andino:
        build: ./ckan-img
        container_name: andino
        ports:
          - 8800:8800
        depends_on:
           - db
           - solr
           - redis
        networks:
          - andino-network
        volumes:
          - $PWD:/dev-app
    db:
        build: ./postgresql-img
        container_name: db
        networks:
          - andino-network
    redis:
        image: redis:3.2.7-alpine
        container_name: redis
        networks:
          - andino-network
    solr:
        build: ./solr-img
        container_name: solr
        networks:
          - andino-network
networks:
  andino-network:
