version: '2'
services:
    andino:
        build: ./ckan-img
        container_name: andino
        ports:
          - 80:80
          - 8800:8800
        depends_on:
           - db
           - solr
        networks:
          - andino-network
    db:
        build: ./postgresql-img
        networks:
          - andino-network
    solr:
        build: ./solr-img
        networks:
          - andino-network


networks:
  andino-network:
