version: '2'
services:
    ckan:
        container_name: ckan-distribuilble
        image: datosgobar/ckan-distribuilble:latest
        ports:
          - 80:80
          - 8800:8800
        depends_on:
           - pg-ckan
           - solr
        external_links:
           - pg-ckan:db
           - solr:solr
    pg-ckan:
        image: datosgobar/pg-ckan:latest
        container_name: pg-ckan
    solr:
        image: datosgobar/solr:latest
        container_name: solr
