version: '2'
services:
    nginx:
      container_name: andino-nginx
      image: datosgobar/portal-andino-nginx:development
      ports:
        - 80:80
      depends_on:
        - andino
      environment:
        - CKAN_HOST=andino
      networks:
        - andino-network
    andino:
      container_name: andino
      image: datosgobar/portal-andino:development
      ports:
        - 8800:8800
      depends_on:
         - db
         - solr
         - redis
         - postfix
      networks:
        - andino-network
    db:
      container_name: andino-db
        image: postgres:9.5
        environment:
          - POSTGRES_DB=ckan
        networks:
          - andino-network
    redis:
      container_name: andino-redis
      image: redis:3.2.7-alpine
      networks:
        - andino-network
    solr:
      container_name: andino-solr
      image: datosgobar/portal-andino-solr:development
      networks:
        - andino-network
    postfix:
      container_name: andino-postfix
      image: catatnight/postfix
      ports:
        - "25:25"
        - "587:587"
      networks:
        - andino-network

networks:
  andino-network:
