version: '2'
services:
    nginx:
      image: datosgobar/portal-andino:development-nginx
      ports:
        - 80:80
      depends_on:
        - andino
      networks:
        - andino-network
    andino:
      image: datosgobar/portal-andino:development-andino
      ports:
        - 8800:8800
      depends_on:
         - db
         - solr
         - redis
         - postfix
      networks:
        - andino-network
    start_harvest:
      image: datosgobar/portal-andino:development-andino
      command: /etc/ckan_init.d/start_cron.sh
      depends_on:
         - fetch_consumer
         - gather_consumer
      networks:
        - andino-network
    gather_consumer:
      image: datosgobar/portal-andino:development-andino
      command: /etc/ckan_init.d/run_gather_consumer.sh
      depends_on:
         - db
         - solr
         - redis
         - postfix
      networks:
        - andino-network
    fetch_consumer:
      image: datosgobar/portal-andino:development-andino
      command: /etc/ckan_init.d/run_fetch_consumer.sh
      depends_on:
         - db
         - solr
         - redis
         - postfix
      networks:
        - andino-network
    db:
        image: postgres:9.5
        environment:
          - POSTGRES_USER=ckan
          - POSTGRES_PASSWORD=ckan
          - POSTGRES_DB=ckan
        networks:
          - andino-network
    redis:
      image: redis:3.2.7-alpine
      networks:
        - andino-network
    rabbitmq:
      image: rabbitmq:3.6.6-alpine
      networks:
        - andino-network
    solr:
      image: datosgobar/portal-andino:development-solr
      networks:
        - andino-network
    postfix:
      image: catatnight/postfix
      ports:
        - "25:25"
        - "587:587"
      networks:
        - andino-network

networks:
  andino-network:
