version: '2'
services:
    nginx:
      container_name: andino-nginx
      image: datosgobar/portal-base-nginx:latest
      ports:
        - 80:80
      depends_on:
        - andino
      networks:
        - andino-network
      environment:
        - CKAN_HOST
    andino:
      container_name: andino
      image: datosgobar/portal-andino:development
      ports:
        - 8800:8800
      depends_on:
        - db
        - solr
        - redis
        - postfix
      networks:
        - andino-network
    db:
      container_name: andino-db
      image: postgres:9.5
      environment:
        - postgres_db=ckan
        - postgres_user
        - postgres_password
      networks:
        - andino-network
    redis:
      container_name: andino-redis
      image: redis:3.2.7-alpine
      networks:
        - andino-network
    solr:
      container_name: andino-solr
      image: datosgobar/portal-base-solr:latest
      networks:
        - andino-network
    postfix:
      container_name: andino-postfix
      image: catatnight/postfix
      ports:
        - "25:25"
        - "587:587"
      networks:
        - andino-network

networks:
  andino-network:
