site_name: Portal Andino
pages:
  - Home: 'index.md'
  - Desarrollo:
    - 'Docker & ansible': 'development/docker_ansible.md'
    - Tests: 'development/tests.md'
  - Uso:
    - Docker: 'usage/docker.md'
