---

CKAN_INIT: /etc/ckan_init.d
CKAN_DIST_MEDIA: /usr/lib/ckan/default/src/ckanext-gobar-theme/ckanext/gobar_theme/public/user_images
CKAN_DIST_CONFIG: /var/lib/ckan/theme_config
DEBIAN_FRONTEND: noninteractive
CKAN_APACHE2_PORT: 80
CKAN_DATAPUSHER_PORT: 8800
CKAN_NGINX_PORT: 8080
CKAN_CONFIG_FILE: production.ini
HOME: /root
CKAN_VERSION: 2.5.1
CKAN_HOME: /usr/lib/ckan/default
CKAN_CONFIG: /etc/ckan/default
CKAN_DATA: /var/lib/ckan
DATAPUSHER_HOME: /usr/lib/ckan/datapusher
CKAN_HARVEST_GCF: /var/log/ckan/std


# TODO: Remove these
#DEFAULT_SERVER_IP: 172.17.0.4
#DEFAULT_POSTGRESQL_IP: 172.17.0.3
#DEFAULT_SOLR_IP: 172.17.0.2

DEFAULT_POSTGRESQL_USER: ckan
DEFAULT_POSTGRESQL_PASSWORD: ckan
DEFAULT_POSTGRESQL_DB: ckan
DEFAULT_POSTGRESQL_PORT: 5432

DEFAULT_SOLR_PORT: 8983

DEFAULT_POSTGRESQL_IP: db
DEFAULT_SERVER_IP: localhost
DEFAULT_SOLR_IP: solr
