---


- name: configure apache
  template:
    src: apache/ckan_default.conf.j2
    dest: /etc/apache2/sites-enabled/ckan_default.conf

- name: Configure CKAN
  template:
    src: ckan/production.ini.j2
    dest: "{{ CKAN_CONFIG }}/{{ CKAN_CONFIG_FILE }}"

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: apache/apache.wsgi.j2, dest: "{{ CKAN_CONFIG }}/apache.wsgi"}
    - {src: ckan/datapusher.wsgi.j2, dest: /etc/ckan/datapusher.wsgi}
    - {src: ckan/export.map.json.j2, dest: "{{ CKAN_HOME }}/src/ckanext-datajson/ckanext/datajson/export_map/export.map.json"}
    - {src: scripts/add_admin.sh.j2, dest: "{{ CKAN_INIT }}/add_admin.sh"}
    - {src: scripts/change_datapusher_url.sh.j2, dest: "{{ CKAN_INIT }}/change_datapusher_url.sh"}
    - {src: scripts/change_site_url.sh.j2, dest: "{{ CKAN_INIT }}/change_site_url.sh"}
    - {src: scripts/init_db.sh.j2, dest: "{{ CKAN_INIT }}/init_db.sh"}
    - {src: scripts/make_test_conf.sh.j2, dest: "{{ CKAN_INIT }}/make_test_conf.sh"}
    - {src: scripts/run_tests.sh.j2, dest: "{{ CKAN_INIT }}/run_tests.sh"}
    - {src: scripts/make_conf.sh.j2, dest: "{{ CKAN_INIT }}/make_conf.sh"}
    - {src: scripts/start_ckan.sh.j2, dest: "{{ CKAN_INIT }}/start_ckan.sh"}
    - {src: scripts/run_andino.sh, dest: "{{ CKAN_INIT }}/run_andino.sh"}
    - {src: scripts/run_gather_consumer.sh.j2, dest: "{{ CKAN_INIT }}/run_gather_consumer.sh"}
    - {src: scripts/run_fetch_consumer.sh.j2, dest: "{{ CKAN_INIT }}/run_fetch_consumer.sh"}

- name: Copy default ckan config
  template:
    src: ckan/default.json.j2
    dest: "{{ CKAN_DIST_CONFIG }}/settings.json"

- name: Change mode default ckan config
  file:
    path: "{{ CKAN_DIST_CONFIG }}/settings.json"
    mode: 0666

- name: Change mode ckan init
  file:
    path: "{{ CKAN_INIT }}"
    recurse: yes
    mode: 0777

- name: Change mode ckan config
  file:
    path: "{{ CKAN_CONFIG }}"
    recurse: yes
    mode: 0777
