---

- name: configure supervisor ckan harvesting
  template:
    src: supervisor/ckan_harvesting.conf.j2
    dest: /etc/supervisor/conf.d/

- name: configure supervisor
  template:
    src: supervisor/supervisord.conf.j2
    dest: /etc/supervisor/conf.d/supervisord.conf

- name: configure apache
  template:
    src: apache/ckan_default.conf.j2
    dest: /etc/apache2/sites-enabled/ckan_default.conf

- name: Configure CKAN
  template:
    src: ckan/production.ini.j2
    dest: "{{ CKAN_CONFIG }}/{{ CKAN_CONFIG_FILE }}"

- name: Add scripts
  copy:
    src: "scripts/{{ item }}"
    dest: "{{ CKAN_INIT }}/"
  with_items:
    - start_servers.sh
    - start_supervisor.sh
    - theme_f_update.sh


- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: apache/apache.wsgi.j2, dest: "{{ CKAN_CONFIG }}/apache.wsgi"}
    - {src: ckan/datapusher.wsgi.j2, dest: /etc/ckan/datapusher.wsgi}
    - {src: ckan/export.map.json.j2, dest: "{{ CKAN_HOME }}/src/ckanext-datajson/ckanext/datajson/export_map/export.map.json"}
    - {src: scripts/.init_db.sh.j2, dest: "{{ CKAN_INIT }}/.init_db.sh"}
    - {src: scripts/.make_conf.sh.j2, dest: "{{ CKAN_INIT }}/.make_conf.sh"}
    - {src: scripts/start_ckan.sh.j2, dest: "{{ CKAN_INIT }}/start_ckan.sh"}

- name: Copy service files
  copy:
    src: "autoload/{{ item }}"
    dest: /etc/service/
  with_items:
    - ckan
    - postfix

- name: Apache ckan error log
  file:
    path: /var/log/apache/ckan_default.error.log
    state: touch

- name: Copy default ckan config
  template:
    src: ckan/default.json.j2
    dest: "{{ CKAN_DIST_CONFIG }}/settings.json"

- name: Change mode default ckan config
  file:
    path: "{{ CKAN_DIST_CONFIG }}/settings.json"
    mode: 0666

- name: Change mode ckan init
  file:
    path: "{{ CKAN_INIT }}"
    recurse: yes
    mode: 0777

- name: Change mode ckan config
  file:
    path: "{{ CKAN_CONFIG }}"
    recurse: yes
    mode: 0777
